### ISSUE TITLE
Is the GNN algorithm the only learnable part of this framework?

### ISSUE THREAD

**Issue by qqaazxddrr** [DeepGraphLearning/GNN-QE#3]
It looks like the only learnable part of your proposed algorithm is the mapping operation, the GNN model. The logical operations use fuzzy logic and do not require learning. So, why not use the trained GNN model directly in the GNN-QE framework?

**Comment by KiddoZhu** [comment]
Hi! Your understanding is right. GNN is the only learnable component of GNN-QE. You may train the GNN-QE on 1p queries only and evaluate it on complex queries (like CQD). It's feasible but the results are not so good, because 1p only deals with one-hot fuzzy sets as input, while projections in other queries may deal with multi-hot fuzzy sets as input.
